### ISSUE TITLE
Support initialStartDate and initialEndDate

### ISSUE THREAD

**Issue by pooyahrtn** [afshinm/JalaliCalendarPicker#3]
Hi. thanks for your great job.
I suggest you change state of constructor at the line : selectedStartDate = this.props.selectedStartDate ...
so we can setup an initial date picked.
also you can add a "fixed" prop which disable picker. simply you can add if(props.fixed){ return} to the handleOnPressDay().
thank you so much.

**Comment by afshinm** [comment]
Could you send a PR?
