### ISSUE TITLE
Invalid prop `initialDate` of type `Moment` supplied to `HeaderControls`

### ISSUE THREAD

**Issue by saeedjamshidi** [afshinm/JalaliCalendarPicker#4]
Hi Afshin, I'm using this component on react native 0.50.3 and I'm getting bellow warning:

> Warning: Failed prop type: Invalid prop `initialDate` of type `Moment` supplied to `HeaderControls`, expected instance of `Date`

could you please help me to figure out how to fix this?

**Comment by afshinm** [comment]
It must be related to this line: https://github.com/afshinm/JalaliCalendarPicker/blob/master/CalendarPicker/HeaderControls.js#L59

Changing the type of this property to `Moment` should solve the issue.
